version: '3.7'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cotas
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./cotas-mysql:/var/lib/mysql
volumes:
  cotas-mysql: 